name: caror
description: Caror App
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.4
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  mobile_scanner: ^1.0.0
  flutter_rating_bar: ^4.0.0
  flutter_staggered_grid_view: ^0.4.1
  encrypt: ^5.0.1
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600